### ISSUE TITLE
Emails not being sent

### ISSUE THREAD

**Issue by koehn** [revpriest/listman#11] opened 2021-07-16 20:10 UTC
When I send a message using the web form to a list with multiple members, nothing happens. There's nothing in `nextcloud.log`, and my mail server is never contacted. 

The admin UI shows:
<img width="297" alt="image" src="https://user-images.githubusercontent.com/583888/126003336-d0602366-e6f7-42cf-9634-069d8b8db659.png">

I'm using the same host/port/username/pw that I use for nextcloud's email server, so I know it's not a configuration issue.

**Comment by revpriest** [comment] 2021-07-18 11:34
Not sure what could cause this one.

Are you comfortable looking at the database?

If you look in the ob_jobs table is the one with the class "OCA\Listman\Cron\ListmanSend"

> select * from oc_jobs

That'd mean it'd failed to create the cron-job to do the actual sending somehow.

But the "rate" being 10 there probably means it's done a send-job a few times, with presuably the 3 mails still not leaving the queue. Not sure what could cause that really.

Does the "rate" change over the course of ten minutes? Does the number in the queue ever change?

Thanks.

**Comment by koehn** [comment] 2021-07-18 13:16
```
select * from oc_jobs where class like '%ListmanSend';
  id  |            class             | argument |  last_run  | last_checked | reserved_at | execution_duration 
------+------------------------------+----------+------------+--------------+-------------+--------------------
 3457 | OCA\Listman\Cron\ListmanSend | null     | 1626609630 |   1626609630 |  1626609630 |                  0
(1 row)
```

The rate is currently `64 per 5 mins` despite me not sending anything for a few days.

**Comment by revpriest** [comment] 2021-07-18 14:17
The rate should double every cron-call until the list is empty.

Sounds like it's running the cron, but failing to send to mail for some reason. It must at least realized it's failed or it'd be marking them as sent and thus eventually running out and setting the rate back to zero.

There is a "max to send per day" setting, presumably you've not got that at zero or anything? It won't send if it's over it's sending limit and if the limit is zero that'd mean never.

There's an exception-catch in there that probably should have some kinda log-the-exception in it. 

Not sure off hand how to actually send something to the nextcloud log. Will have to figure that out. No time today I'm afraid.

**Comment by koehn** [comment] 2021-07-18 14:22
Max send per day is set at 50. Logging would be helpful. I have some other UI/UX related asks that I'll file separately. I think you've got a useful tool under way; looking forward to seeing an even better version! Thank you for all the work!

**Comment by revpriest** [comment] 2021-07-20 10:19
Added some logging of exceptions during the sending of email.

Had a thought about what it could be too: Most email providers only allow "from" addresses that are whitelisted by you clicking an emailed-link. If the "from" address the list sends from isn't in the email-provider's whitelist they might reject the mail.

Did the subscription-confirmation emails get sent? They get sent with the same system I think, just not in a cron.

Anyway, hopefully there'll be something useful in the nextcloud error log if you update.

**Comment by chrisSCM** [comment] 2021-08-23 12:45
For me, emails aren't sent either. But I don't even have a table "oc_jobs" - my Nextcloud version is 21.0.4.

For the SMTP-config, I wonder, doesn't seem to be possible to add like SSL or STARTTLS, how is it going to work then?

Thank you.

**Comment by revpriest** [comment] 2021-08-23 20:11
It uses PHPMailer, which does opportunistic TLS - if the server advertises that it can do TLS, it will use it automatically.

I think I agree they should probably be options though, to disable TLS if needed or specify SSL instead perhaps.

Will look into that when I get a chance.

Not sure what could make your system not have the "jobs" table. If all your tables have a different prefix then maybe it's "X_jobs" or whatever the prefix is instead?

I think that table should be there for your next-cloud to keep track of what cron-jobs need doing, possibly there's some step in installing which involves  setting up a cron? Can't rememeber if I did anything like that in my initial setup.

The emails are sent by the cron system, so if the cron system isn't working for some reason the emails won't be sent.

**Comment by jlgarnier** [comment] 2021-09-27 06:41
Hi all,
Sorry to add one line to the charge 😉 ut got the same issue on my Docker Nextcloud instance:
- Mails are not sent despite the same email config than the admin (works fine),
- Cron task fails with following error message:
`Error: Failed opening required '/var/www/html/custom_apps/listman/lib/Service/../../vendor/autoload.php' (include_path='/var/www/html/3rdparty/pear/archive_tar:/var/www/html/3rdparty/pear/console_getopt:/var/www/html/3rdparty/pear/pear-core-minimal/src:/var/www/html/3rdparty/pear/pear_exception:/var/www/html/apps:/var/www/html/custom_apps') in /var/www/html/custom_apps/listman/lib/Service/ListmanService.php:782
Stack trace:
#0 /var/www/html/custom_apps/listman/lib/Service/ListmanService.php(1051): OCA\Listman\Service\ListmanService->getMailer(Object(OCA\Listman\Db\Maillist), Object(OCA\Listman\Db\Member), Object(OCA\Listman\Db\Message))
#1 /var/www/html/custom_apps/listman/lib/Service/ListmanService.php(1113): OCA\Listman\Service\ListmanService->sendEmailToMember(Object(OCA\Listman\Db\Sendjob))
#2 /var/www/html/custom_apps/listman/lib/Cron/ListmanSend.php(28): OCA\Listman\Service\ListmanService->runCron()
#3 /var/www/html/lib/public/BackgroundJob/Job.php(79): OCA\Listman\Cron\ListmanSend->run(NULL)
#4 /var/www/html/cron.php(127): OCP\BackgroundJob\Job->execute(Object(OC\BackgroundJob\JobList), Object(OC\Log))
#5 {main}
`

Hope this can help to solve it! Thanks Rev for the great job!

**Comment by revpriest** [comment] 2021-09-27 15:19
Humm. I think that probably means that the file /var/www/html/custom_apps/listman/vendor/autoload.php isn't there, so it can't find the phpmailer.

Someone told me not to pack the Vendor directory inside the release-package, and I did as they suggested assuming that there must therefore be some sort of build-step in the install which build the vendor directory.

Sounds like that might have been wrong, and that at least part of the Vendor directory should perhaps be included in the tar package.

Won't have any time to look into it for a few days, but it'll definitely want to have the vendor directory with phpmailer in it, so if that's missing then figuring out how to get that, ideally without all the other junk in Vendor, will be what needs to be done.

**Comment by jlgarnier** [comment] 2021-09-27 15:23
Thanks for the feedback! Is there any way to get this particular module and add it to the existing installation?

**Comment by revpriest** [comment] 2021-09-27 15:29
Probably, maybe?

Running "make composer" from the listman directory might do it? Depending on if the right tools are installed. Not sure what tools those would be.

Suspect that kinda thing is more difficult from the Docker install but never used it so dunno?

**Comment by jlgarnier** [comment] 2021-09-27 16:47
Yes, the Docker env may raise tricky issues, especially with dependencies. Do you have any "full-featured" package which I could untar and overwrite the current installation?

**Comment by revpriest** [comment] 2021-09-27 21:27
Everything necessary is in this repo I think. Cloning it out into the app folder then running "make composer" should download all the stuff in the composer.json to fill the vendor directory.

It's "make composer" that I assumed must be done in a build-step when installing from the package when I was told to remove the Vendor directory from the release tarball.

I wonder if Keohn is using the Docker install too? Maybe I should try running nextcloud through Docker one day.

Might have a couple of hours to look into it Wednesday or Thursday night.

**Comment by jlgarnier** [comment] 2021-09-28 06:36
Will maybe give it a try this afternoon and let you know how it went... 👍

**Comment by revpriest** [comment] 2021-09-29 19:27
Something else came up tonight, unlikely to be able to get to this until the weekend at the earliest, sorry. :(

**Comment by revpriest** [comment] 2021-10-20 19:42
I managed to find some time.

Have re-packaged to new version 20.0.8 - that should include the vendor/phpmailer directory now.

Seems to sill be downloading v 20.0.0.7 when I try from my dev/test system though. Maybe coz I did a test-download of that and it's cached somewhere?

If you manage to get V20.0.8 to download hopefully it should contain the mailer library and so be able to send mail now?

Or maybe I'll get an email explaining why the repackage thing didn't work?

Will try and double-check tomorrow when hopefully whatever this cache is has timed out.

I wonder how you attach release-notes to a version update?....

**Comment by jlgarnier** [comment] 2021-11-03 08:59
Hi,
Back from a short vacation, I'll try to download this 20.0.8 version: still the normal `git clone https://github.com/revpriest/listman.git listman` command? I can't see any vendor/phpmailer directory on the Code tab...
Since your message, did you solve your cache issue and have the opportunity to check this new release?
Thanks again for your help!

**Comment by revpriest** [comment] 2021-11-03 10:41
Uh, assumed you were installing just by clicking the install button in the addons page to install the package from the link uploaded to Nextcloud's servers.

It's entirely possible I haven't been pushing to github. Lets check....

Indeed, I haven't. Oops. Have pushed here now.

But if you're cloning from Github then the fact that the phpmailer library isn't included isn't the problem, since that's not in the git anyway.

If you've cloned from Github instead of using the "install" button then you'll need to build the contrib stuff with
> make composer
from the newly checked out directory. That is what fetches the phpmailer library (as well as various other dev stuff)

 I don't understand why "make composer" wouldn't create the phpmailer directory though.

**Comment by david-aigner** [comment] 2021-11-11 15:24
Hi @revpriest 

I love the idea - thank you for the app!

Unfortunately for me, it is also not sending. The app mentions queued 2 | Rate 1 per 5 minutes

The jobs entry says 4495 | OCA\Listman\Cron\ListmanSend | null | 0 | 1636638423 | 0 | 0

Unfortunately nothing in the protocol

Anything I can check myself? 

Thank you!

**Comment by revpriest** [comment] 2021-11-11 19:39
I suspect it's not working for anyone other than me, but I don't know why. Guess you mostly don't see the successes so my sampling is biased?

Anyway.

That first zero means it has never run the cron-job. Not sure why that would be.

If you have shell access then you could run
> sudo -u www-data php -f cron.php
(or similar, your web-user might not be called "www-data" if you're not debian, I dunno)

From the main nextcloud directory and that might force the cron-jobs to run, or show you an error message.

**Comment by david-aigner** [comment] 2021-11-12 11:38
Thanks for the direction - now I at least have a error message :-D

PHP Fatal error:  require(): Failed opening required '/.../cloud/apps/listman/lib/Service/../../vendor/autoload.php' (include_path='/.../cloud/3rdparty/pear/archive_tar:/.../cloud/3rdparty/pear/console_getopt:/.../cloud/3rdparty/pear/pear-core-minimal/src:/.../cloud/3rdparty/pear/pear_exception:/.../cloud/apps') in /.../cloud/apps/listman/lib/Service/ListmanService.php on line 782

**Comment by fabricerouillier** [comment] 2021-11-12 15:15
The autoload.php is missing.

**Comment by david-aigner** [comment] 2021-11-12 18:14
checked the vendor folder - only one directory "phpmailer" in it. On your github page, I can not find the vendor folder at all - is it created locally during setup? how can I get the file?

Thank you!

**Comment by revpriest** [comment] 2021-11-12 18:18
Will try and build a new package with the autoload in it too next week. 

The build steps for generating the dependencies is described in the README.

> make composer
> make dev-setup

**Comment by fabricerouillier** [comment] 2021-11-12 19:37
> Will try and build a new package with the autoload in it too next week.
> 
> The build steps for generating the dependencies is described in the README.
> 
> > make composer
> > make dev-setup

I have performed the operations in my nextcloud docker container (note you have to install nodejs version 14 at most)

I was able to use the subscribe form to register.

But I still have my old  messages Queued (from previous attempts) and it still Queues new messages without sending them.

How to empty the queue ?

**Comment by revpriest** [comment] 2021-11-16 12:49
Okay, thanks for your help everyone.

I've pushed a new version 20.1.0 which includes a bunch of stuff in the Vendor directory:
autoload.php
composer/*
myclabs/*

And now my new test/staging install works and sends messages.

I also added a new box in the "settings", which shows the latest warning generated by the sender. That'll usually be something like "didn't send to x@y.c because already passed sending limits" or "authentication error:" or if there's an exception the message from the exception.

Hopefully that'll help figure out any other issues like wrong SMPT details etc.

Only way to delete the queue is by editing the SQL database I'm afraid. 

This will kill all unsent message-sending tasks:
> delete from oc_listman_sendjob where state=0;

This will remove all the ones which had some kind of error or passed sending limits:
> delete from oc_listman_sendjob where state<0;

This will remove the whole lot which may mean people get duplicate messages, it will allow re-sending the same message to the same address:
> delete from oc_listman_sendjob;

You may also want to wipe the records of when we last sent a message to someone, so you can for a re-send even if the flood-protection thinks they were already emailed today and is refusing to do it again:

This will wipe all last-send dates:
> update oc_listman_member set lastsend=null

This will do it just for a single email:
> update oc_listman_member set lastsend=null where email="x@y.z"

Hopefully that'll make it work for everyone. Please let me know so I can close the issue.

**Comment by david-aigner** [comment] 2021-11-16 15:52
Thank you, @revpriest !

I had a short struggle with my cron job to run it again, but now it is sending!

For me, the issue is solved!

Thank you!

**Comment by revpriest** [comment] 2021-11-17 10:12
Hurray. Hopefully it's good for everyone then.

Shout up if not, I think these things can be re-opened.

**Closed by revpriest** 2021-11-17 10:12 UTC
